### ISSUE TITLE
Logo (kinda) fixed

### ISSUE THREAD

**Issue by EimaMei** [ColleagueRiley/RSGL-Riley-s-Simple-GUI-Library-#4]
Made the logo look a bit better:tm:
Old:
![logo](https://user-images.githubusercontent.com/69605234/137603751-8874b431-6890-4b64-9482-49ffa19dfd52.png)
New:
![image](https://user-images.githubusercontent.com/69605234/137603773-1a54f158-6bd8-4c37-8d46-06cf0b03627c.png)

**Comment by ColleagueRiley** [comment]
Thanks my nucka
